ENCODER_ENABLE     = yes
TAP_DANCE_ENABLE   = yes
RGB_MATRIX_ENABLE  = no
COMBO_ENABLE       = yes
RGBLIGHT_ENABLE    = yes
RGBLIGHT_DRIVER    = ws2812
ENCODER_MAP_ENABLE = yes
MOUSEKEY_ENABLE    = yes
